trigger:
  branches:
    include:
      - main
      - feature/Java

pool: Azure Pipelines

stages:
  - stage: Build
    jobs:
      - job: MavenBuild
        displayName: Maven Build
        steps:

        - task: SonarQubePrepare@8
          displayName: Prepare SonarQube Analysis
          inputs:
            SonarQube: 'SonarCloud-SC'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'BhabyaBharti_JavaLoginPracticeApp'
            cliProjectName: 'JavaLoginPracticeApp'
            cliSources: '.'
            extraProperties: |
              sonar.organization=bhabyabharti
              sonar.host.url='https://sonarcloud.io'
              sonar.tests=
              sonar.test.exclusions=**/*

        - task: Maven@4
          displayName: mvn build & Run Sonar Analysis
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify sonar:sonar'
            options: '-Dsonar.host.url=https://sonarcloud.io -Dsonar.login="6d738a0fb7e64392588deda6688aefc897c22844" -Dsonar.organization=bhabyabharti -Dsonar.projectKey=BhabyaBharti_JavaLoginPracticeApp'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            publishJUnitResults: false

        - task: ArchiveFiles@2
          displayName: Archive the Artifacts
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)/target'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          displayName: Publish Build Artifacts
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/target'
            ArtifactName: 'MavenBuildArtifact'
            publishLocation: 'Container'

  - stage: Linting
    displayName: Lint Java App
    dependsOn: Build
    jobs:
      - job: Linting_Java_App
        steps:
        - task: PowerShell@2
          displayName: Install and Run StyleLint
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "Initializing npm project..."
              npm init -y

              Write-Host "Installing Stylelint and standard configs..."
              npm install stylelint stylelint-config-standard stylelint-config-recommended --save-dev

              Write-Host "Creating .stylelintrc.json..."
              @"
              {
                "extends": [
                  "stylelint-config-standard",
                  "stylelint-config-recommended"
                ]
              }
              "@ | Out-File -FilePath ".stylelintrc.json" -Encoding UTF8

              Write-Host "Running Stylelint (errors will NOT fail pipeline)..."
              # Run stylelint but ALWAYS return success
              npx stylelint "**/*.css" "**/*.scss"
              # Force task to succeed even if errors are present
              $LASTEXITCODE = 0

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    variables:
      - name: WAR_FILE_NAME
        value: 'app.war'

    jobs:
      - deployment: DeployToProd
        displayName: Deploy on Tomcat
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: Get the Artifacts
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'MavenBuildArtifact'
                  itemPattern: 
                  downloadPath: '$(Pipeline.Workspace)'

              - task: PowerShell@2
                displayName: Find WAR File
                inputs:
                  targetType: 'inline'
                  script: |
                    Write-Host "=== Searching for WAR files ==="
                    $artifactPath = "$(Pipeline.Workspace)/MavenBuildArtifact"
                    Write-Host "Artifact path: $artifactPath"
                    
                    if (-not (Test-Path $artifactPath)) {
                      Write-Error "Artifact path does not exist: $artifactPath"
                      Write-Host "Available directories in Pipeline.Workspace:"
                      Get-ChildItem -Path "$(Pipeline.Workspace)" -Directory | Format-Table Name
                      exit 1
                    }
                    
                    # List all files
                    Write-Host "All files in artifact:"
                    Get-ChildItem -Path $artifactPath -Recurse | Select-Object -First 20 | Format-Table Name, Extension, Length
                    
                    # Find WAR files
                    $warFiles = Get-ChildItem -Path $artifactPath -Filter "*.war" -Recurse
                    if ($warFiles.Count -eq 0) {
                      Write-Warning "No WAR files found in artifact!"
                      Write-Host "Looking for any JAR files instead..."
                      $jarFiles = Get-ChildItem -Path $artifactPath -Filter "*.jar" -Recurse
                      if ($jarFiles.Count -gt 0) {
                        Write-Host "Found JAR files instead:"
                        $jarFiles | ForEach-Object { Write-Host "  - $($_.FullName)" }
                      }
                      exit 1
                    } else {
                      Write-Host "Found $($warFiles.Count) WAR file(s):"
                      $warFiles | ForEach-Object { 
                        Write-Host "  - $($_.FullName)"
                        Write-Host "##vso[task.setvariable variable=WAR_FILE_NAME]$($_.Name)"
                        Write-Host "##vso[task.setvariable variable=WAR_FULL_PATH]$($_.FullName)"
                      }
                    }

              - task: SSH@0
                displayName: Install Tomcat from Ubuntu repo
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  runOptions: 'inline'
                  inline: |
                    echo "=== Installing Tomcat from Ubuntu Repository ==="
                    
                    # Check if Tomcat is already installed
                    if systemctl list-unit-files | grep -q tomcat9; then
                      echo "Tomcat 9 is already installed via package manager"
                    else
                      echo "Installing Tomcat 9 from Ubuntu repository..."
                      
                      # Update and install
                      sudo apt-get update
                      sudo apt-get install -y tomcat9 tomcat9-admin
                      
                      echo "Tomcat 9 installed successfully"
                    fi
                    
                    # Check status
                    echo "=== Tomcat Status ==="
                    sudo systemctl status tomcat9 --no-pager || echo "Tomcat9 service not found"
                    
                    # If not running, start it
                    if ! systemctl is-active --quiet tomcat9; then
                      echo "Starting Tomcat 9..."
                      sudo systemctl start tomcat9
                      sudo systemctl enable tomcat9
                      sleep 3
                    fi
                    
                    # Verify
                    if systemctl is-active --quiet tomcat9; then
                      echo "✓ Tomcat 9 is running"
                      echo "Webapps directory: /var/lib/tomcat9/webapps"
                      echo "Access URL: http://$(hostname -I | awk '{print $1}'):8080"
                    else
                      echo "✗ Tomcat 9 failed to start"
                    fi
                  readyTimeout: '20000'

              - task: CopyFilesOverSSH@0
                displayName: Copy WAR to Temp Location
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  sourceFolder: '$(Pipeline.Workspace)/MavenBuildArtifact'
                  contents: '**/*.war'
                  targetFolder: '~/tmp_deploy/'
                  readyTimeout: '20000'
                  
              - task: SSH@0
                displayName: Deploy WAR and Restart Tomcat
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  runOptions: 'inline'
                  inline: |
                    echo "=== Deploying WAR File ==="
                    
                    # Determine Tomcat webapps directory
                    if [ -d "/var/lib/tomcat9/webapps" ]; then
                      WEBAPPS_DIR="/var/lib/tomcat9/webapps"
                      TOMCAT_SERVICE="tomcat9"
                      echo "Using Tomcat 9 installation"
                    elif [ -d "/opt/tomcat/webapps" ]; then
                      WEBAPPS_DIR="/opt/tomcat/webapps"
                      TOMCAT_SERVICE=""
                      echo "Using custom Tomcat installation"
                    else
                      echo "ERROR: No Tomcat webapps directory found!"
                      exit 1
                    fi
                    
                    echo "Webapps directory: $WEBAPPS_DIR"
                    
                    # Stop Tomcat before deployment if using systemd service
                    if [ -n "$TOMCAT_SERVICE" ]; then
                      echo "Stopping Tomcat service..."
                      sudo systemctl stop $TOMCAT_SERVICE
                      sleep 3
                    fi
                    
                    # Deploy WAR files
                    if [ -d ~/tmp_deploy ]; then
                      for war_file in ~/tmp_deploy/*.war; do
                        if [ -f "$war_file" ]; then
                          war_name=$(basename "$war_file")
                          app_name="${war_name%.*}"
                          
                          echo "Deploying: $war_name"
                          
                          # Remove old deployment
                          sudo rm -rf "$WEBAPPS_DIR/$app_name"
                          sudo rm -f "$WEBAPPS_DIR/$war_name"
                          
                          # Copy new WAR
                          sudo cp "$war_file" "$WEBAPPS_DIR/"
                          sudo chown tomcat:tomcat "$WEBAPPS_DIR/$war_name" || sudo chown tomcat9:tomcat9 "$WEBAPPS_DIR/$war_name"
                          sudo chmod 644 "$WEBAPPS_DIR/$war_name"
                          
                          echo "✓ Deployed: $war_name"
                        fi
                      done
                      
                      # Clean up temp directory
                      rm -rf ~/tmp_deploy
                      
                      # Start Tomcat
                      if [ -n "$TOMCAT_SERVICE" ]; then
                        echo "Starting Tomcat service..."
                        sudo systemctl start $TOMCAT_SERVICE
                      else
                        echo "Starting Tomcat..."
                        sudo -u tomcat /opt/tomcat/bin/startup.sh || echo "Using existing Tomcat process"
                      fi
                      
                      sleep 5
                      
                      # Verify
                      echo "=== Deployment Complete ==="
                      echo "Application deployed to: $WEBAPPS_DIR"
                      echo "Access at: http://$(hostname -I | awk '{print $1}'):8080/JavaLoginShowcase-1.0.0/"
                    else
                      echo "ERROR: No WAR files to deploy"
                      exit 1
                    fi
                  readyTimeout: '20000'