trigger:
  branches:
    include:
      - main
      - feature/Java

pool: Azure Pipelines

stages:
  - stage: Build
    jobs:
      - job: MavenBuild
        displayName: Maven Build
        steps:

        - task: SonarQubePrepare@8
          displayName: Prepare SonarQube Analysis
          inputs:
            SonarQube: 'SonarCloud-SC'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'BhabyaBharti_JavaLoginPracticeApp'
            cliProjectName: 'JavaLoginPracticeApp'
            cliSources: '.'
            extraProperties: |
              sonar.organization=bhabyabharti
              sonar.host.url='https://sonarcloud.io'
              sonar.tests=
              sonar.test.exclusions=**/*

        - task: Maven@4
          displayName: mvn build & Run Sonar Analysis
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify sonar:sonar'
            options: '-Dsonar.host.url=https://sonarcloud.io -Dsonar.login="6d738a0fb7e64392588deda6688aefc897c22844" -Dsonar.organization=bhabyabharti -Dsonar.projectKey=BhabyaBharti_JavaLoginPracticeApp'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            publishJUnitResults: false

        - task: ArchiveFiles@2
          displayName: Archive the Artifacts
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)/target'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          displayName: Publish Build Artifacts
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/target'
            ArtifactName: 'MavenBuildArtifact'
            publishLocation: 'Container'

  - stage: Linting
    displayName: Lint Java App
    dependsOn: Build
    jobs:
      - job: Linting_Java_App
        steps:
        - task: PowerShell@2
          displayName: Install and Run StyleLint
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "Initializing npm project..."
              npm init -y

              Write-Host "Installing Stylelint and standard configs..."
              npm install stylelint stylelint-config-standard stylelint-config-recommended --save-dev

              Write-Host "Creating .stylelintrc.json..."
              @"
              {
                "extends": [
                  "stylelint-config-standard",
                  "stylelint-config-recommended"
                ]
              }
              "@ | Out-File -FilePath ".stylelintrc.json" -Encoding UTF8

              Write-Host "Running Stylelint (errors will NOT fail pipeline)..."
              # Run stylelint but ALWAYS return success
              npx stylelint "**/*.css" "**/*.scss"
              # Force task to succeed even if errors are present
              $LASTEXITCODE = 0

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    variables:
      - name: WAR_FILE_NAME
        value: 'app.war'  # Change this to your actual WAR file name

    jobs:
      - deployment: DeployToProd
        displayName: Deploy on Tomcat
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: Get the Artifacts
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'MavenBuildArtifact'
                  itemPattern: 
                  downloadPath: '$(Pipeline.Workspace)'

              - task: PowerShell@2
                displayName: Find WAR File
                inputs:
                  targetType: 'inline'
                  script: |
                    Write-Host "=== Searching for WAR files ==="
                    $artifactPath = "$(Pipeline.Workspace)/MavenBuildArtifact"
                    Write-Host "Artifact path: $artifactPath"
                    
                    if (-not (Test-Path $artifactPath)) {
                      Write-Error "Artifact path does not exist: $artifactPath"
                      Write-Host "Available directories in Pipeline.Workspace:"
                      Get-ChildItem -Path "$(Pipeline.Workspace)" -Directory | Format-Table Name
                      exit 1
                    }
                    
                    # List all files
                    Write-Host "All files in artifact:"
                    Get-ChildItem -Path $artifactPath -Recurse | Select-Object -First 20 | Format-Table Name, Extension, Length
                    
                    # Find WAR files
                    $warFiles = Get-ChildItem -Path $artifactPath -Filter "*.war" -Recurse
                    if ($warFiles.Count -eq 0) {
                      Write-Warning "No WAR files found in artifact!"
                      Write-Host "Looking for any JAR files instead..."
                      $jarFiles = Get-ChildItem -Path $artifactPath -Filter "*.jar" -Recurse
                      if ($jarFiles.Count -gt 0) {
                        Write-Host "Found JAR files instead:"
                        $jarFiles | ForEach-Object { Write-Host "  - $($_.FullName)" }
                      }
                      exit 1
                    } else {
                      Write-Host "Found $($warFiles.Count) WAR file(s):"
                      $warFiles | ForEach-Object { 
                        Write-Host "  - $($_.FullName)"
                        # Set variable for WAR file name
                        Write-Host "##vso[task.setvariable variable=WAR_FILE_NAME]$($_.Name)"
                        Write-Host "##vso[task.setvariable variable=WAR_FULL_PATH]$($_.FullName)"
                      }
                    }

              - task: CopyFilesOverSSH@0
                displayName: Copy WAR to Temp Location
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  sourceFolder: '$(Pipeline.Workspace)/MavenBuildArtifact'
                  contents: '**/*.war'
                  targetFolder: '~/tmp_deploy/'
                  readyTimeout: '20000'
                  
              - task: SSH@0
                displayName: Deploy WAR to Tomcat with Proper Permissions
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  runOptions: 'inline'
                  inline: |
                    # Check if tomcat user exists, create if not
                      if ! id -u tomcat >/dev/null 2>&1; then
                        echo "Creating tomcat user and group..."
                        sudo groupadd tomcat
                        sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
                      else
                        echo "Tomcat user already exists"
                      fi
                      
                      # Ensure webapps directory exists with correct permissions
                      sudo mkdir -p /opt/tomcat/webapps
                      sudo chown -R tomcat:tomcat /opt/tomcat/webapps
                      sudo chmod 755 /opt/tomcat/webapps
                      
                      # Find and move WAR files from temp location
                      echo "Looking for WAR files in ~/tmp_deploy/"
                      if [ -d ~/tmp_deploy ]; then
                        for war_file in ~/tmp_deploy/*.war; do
                          if [ -f "$war_file" ]; then
                            war_name=$(basename "$war_file")
                            echo "Deploying $war_name to Tomcat..."
                            
                            # Remove old deployment if exists
                            sudo rm -rf "/opt/tomcat/webapps/${war_name%.*}"
                            sudo rm -f "/opt/tomcat/webapps/$war_name"
                            
                            # Copy WAR with tomcat ownership
                            sudo cp "$war_file" /opt/tomcat/webapps/
                            sudo chown tomcat:tomcat "/opt/tomcat/webapps/$war_name"
                            sudo chmod 644 "/opt/tomcat/webapps/$war_name"
                            
                            echo "Successfully deployed $war_name"
                          fi
                        done
                        
                        # Clean up temp directory
                        rm -rf ~/tmp_deploy
                      else
                        echo "ERROR: Temp directory ~/tmp_deploy not found!"
                        exit 1
                      fi
                      
                      # Check if Tomcat is installed as a service
                      if systemctl list-unit-files | grep -q tomcat; then
                        echo "Restarting Tomcat service..."
                        sudo systemctl restart tomcat
                        echo "Tomcat status:"
                        sudo systemctl status tomcat --no-pager
                      else
                        echo "Tomcat service not found. WAR will be deployed when Tomcat starts."
                        echo "You may need to start Tomcat manually."
                      fi
                      
                      echo "Deployment completed successfully!"
                    readyTimeout: '20000'