trigger:
  branches:
    include:
      - main
      - feature/Java

pool: Azure Pipelines

stages:
  - stage: Build
    jobs:
      - job: MavenBuild
        displayName: Maven Build
        steps:

        - task: SonarQubePrepare@8
          displayName: Prepare SonarQube Analysis
          inputs:
            SonarQube: 'SonarCloud-SC'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'BhabyaBharti_JavaLoginPracticeApp'
            cliProjectName: 'JavaLoginPracticeApp'
            cliSources: '.'
            extraProperties: |
              sonar.organization=bhabyabharti
              sonar.host.url='https://sonarcloud.io'
              sonar.tests=
              sonar.test.exclusions=**/*

        - task: Maven@4
          displayName: mvn build & Run Sonar Analysis
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify sonar:sonar'
            options: '-Dsonar.host.url=https://sonarcloud.io -Dsonar.login="6d738a0fb7e64392588deda6688aefc897c22844" -Dsonar.organization=bhabyabharti -Dsonar.projectKey=BhabyaBharti_JavaLoginPracticeApp'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            publishJUnitResults: false

        - task: ArchiveFiles@2
          displayName: Archive the Artifacts
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)/target'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          displayName: Publish Build Artifacts
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/target'
            ArtifactName: 'MavenBuildArtifact'
            publishLocation: 'Container'

  - stage: Linting
    displayName: Lint Java App
    dependsOn: Build
    jobs:
      - job: Linting_Java_App
        steps:
        - task: PowerShell@2
          displayName: Install and Run StyleLint
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "Initializing npm project..."
              npm init -y

              Write-Host "Installing Stylelint and standard configs..."
              npm install stylelint stylelint-config-standard stylelint-config-recommended --save-dev

              Write-Host "Creating .stylelintrc.json..."
              @"
              {
                "extends": [
                  "stylelint-config-standard",
                  "stylelint-config-recommended"
                ]
              }
              "@ | Out-File -FilePath ".stylelintrc.json" -Encoding UTF8

              Write-Host "Running Stylelint (errors will NOT fail pipeline)..."
              # Run stylelint but ALWAYS return success
              npx stylelint "**/*.css" "**/*.scss"
              # Force task to succeed even if errors are present
              $LASTEXITCODE = 0

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    variables:
      - name: WAR_FILE_NAME
        value: 'app.war'

    jobs:
      - deployment: DeployToProd
        displayName: Deploy on Tomcat
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: Get the Artifacts
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'MavenBuildArtifact'
                  itemPattern: 
                  downloadPath: '$(Pipeline.Workspace)'

              - task: PowerShell@2
                displayName: Find WAR File
                inputs:
                  targetType: 'inline'
                  script: |
                    Write-Host "=== Searching for WAR files ==="
                    $artifactPath = "$(Pipeline.Workspace)/MavenBuildArtifact"
                    Write-Host "Artifact path: $artifactPath"
                    
                    if (-not (Test-Path $artifactPath)) {
                      Write-Error "Artifact path does not exist: $artifactPath"
                      Write-Host "Available directories in Pipeline.Workspace:"
                      Get-ChildItem -Path "$(Pipeline.Workspace)" -Directory | Format-Table Name
                      exit 1
                    }
                    
                    # List all files
                    Write-Host "All files in artifact:"
                    Get-ChildItem -Path $artifactPath -Recurse | Select-Object -First 20 | Format-Table Name, Extension, Length
                    
                    # Find WAR files
                    $warFiles = Get-ChildItem -Path $artifactPath -Filter "*.war" -Recurse
                    if ($warFiles.Count -eq 0) {
                      Write-Warning "No WAR files found in artifact!"
                      Write-Host "Looking for any JAR files instead..."
                      $jarFiles = Get-ChildItem -Path $artifactPath -Filter "*.jar" -Recurse
                      if ($jarFiles.Count -gt 0) {
                        Write-Host "Found JAR files instead:"
                        $jarFiles | ForEach-Object { Write-Host "  - $($_.FullName)" }
                      }
                      exit 1
                    } else {
                      Write-Host "Found $($warFiles.Count) WAR file(s):"
                      $warFiles | ForEach-Object { 
                        Write-Host "  - $($_.FullName)"
                        Write-Host "##vso[task.setvariable variable=WAR_FILE_NAME]$($_.Name)"
                        Write-Host "##vso[task.setvariable variable=WAR_FULL_PATH]$($_.FullName)"
                      }
                    }

              - task: SSH@0
                displayName: Install Tomcat if needed
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  runOptions: 'inline'
                  inline: |
                    echo "=== Checking Tomcat Installation ==="
                    
                    # Check if Tomcat is already installed
                    if [ -f "/opt/tomcat/bin/startup.sh" ]; then
                      echo "Tomcat is already installed at /opt/tomcat"
                    else
                      echo "Installing Tomcat 9..."
                      
                      # Install Java if not present
                      if ! command -v java &> /dev/null; then
                        echo "Installing Java..."
                        sudo apt-get update
                        sudo apt-get install -y openjdk-11-jdk
                      fi
                      
                      # Create tomcat user if not exists
                      if ! id -u tomcat >/dev/null 2>&1; then
                        sudo groupadd tomcat
                        sudo useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
                      fi
                      
                      # Create directory and download Tomcat
                      sudo mkdir -p /opt/tomcat
                      cd /tmp
                      sudo wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
                      sudo tar -xzf apache-tomcat-9.0.68.tar.gz -C /opt/tomcat --strip-components=1
                      
                      # Set permissions
                      sudo chown -R tomcat:tomcat /opt/tomcat
                      sudo chmod +x /opt/tomcat/bin/*.sh
                      
                      echo "Tomcat installed successfully!"
                    fi
                    
                    # Check if Tomcat is running
                    if ps aux | grep -q "[c]atalina"; then
                      echo "Tomcat is already running"
                    else
                      echo "Starting Tomcat..."
                      sudo -u tomcat /opt/tomcat/bin/startup.sh
                      sleep 5
                    fi
                    
                    # Verify Tomcat is running
                    echo "=== Verification ==="
                    if ps aux | grep -q "[c]atalina"; then
                      echo "✓ Tomcat is running"
                      echo "Tomcat URL: http://$(curl -s ifconfig.me):8080"
                    else
                      echo "✗ Tomcat failed to start"
                      echo "Check logs: /opt/tomcat/logs/catalina.out"
                    fi
                  readyTimeout: '20000'

              - task: CopyFilesOverSSH@0
                displayName: Copy WAR to Temp Location
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  sourceFolder: '$(Pipeline.Workspace)/MavenBuildArtifact'
                  contents: '**/*.war'
                  targetFolder: '~/tmp_deploy/'
                  readyTimeout: '20000'
                  
              - task: SSH@0
                displayName: Deploy WAR and Restart Tomcat
                inputs:
                  sshEndpoint: 'ssh_to_vm_sc'
                  runOptions: 'inline'
                  inline: |
                    echo "=== Deploying WAR File ==="
                    
                    # Ensure webapps directory exists
                    sudo mkdir -p /opt/tomcat/webapps
                    sudo chown -R tomcat:tomcat /opt/tomcat/webapps
                    sudo chmod 755 /opt/tomcat/webapps
                    
                    # Check for WAR files in temp location
                    if [ -d ~/tmp_deploy ]; then
                      WAR_COUNT=$(ls ~/tmp_deploy/*.war 2>/dev/null | wc -l)
                      if [ $WAR_COUNT -eq 0 ]; then
                        echo "No WAR files found in ~/tmp_deploy/"
                        exit 1
                      fi
                      
                      echo "Found $WAR_COUNT WAR file(s)"
                      
                      # Stop Tomcat before deployment
                      echo "Stopping Tomcat for deployment..."
                      if [ -f "/opt/tomcat/bin/shutdown.sh" ]; then
                        sudo -u tomcat /opt/tomcat/bin/shutdown.sh
                        sleep 3
                      fi
                      
                      # Deploy each WAR file
                      for war_file in ~/tmp_deploy/*.war; do
                        if [ -f "$war_file" ]; then
                          war_name=$(basename "$war_file")
                          app_name="${war_name%.*}"
                          
                          echo "Deploying: $war_name"
                          
                          # Remove old deployment
                          sudo rm -rf "/opt/tomcat/webapps/$app_name"
                          sudo rm -f "/opt/tomcat/webapps/$war_name"
                          
                          # Copy new WAR
                          sudo cp "$war_file" /opt/tomcat/webapps/
                          sudo chown tomcat:tomcat "/opt/tomcat/webapps/$war_name"
                          sudo chmod 644 "/opt/tomcat/webapps/$war_name"
                          
                          echo "✓ Deployed: $war_name"
                        fi
                      done
                      
                      # Clean up temp directory
                      rm -rf ~/tmp_deploy
                      
                      # Start Tomcat
                      echo "Starting Tomcat..."
                      sudo -u tomcat /opt/tomcat/bin/startup.sh
                      sleep 8
                      
                      # Verify deployment
                      echo "=== Deployment Verification ==="
                      echo "Deployed applications:"
                      ls -la /opt/tomcat/webapps/
                      
                      # Check Tomcat status
                      if ps aux | grep -q "[c]atalina"; then
                        echo "✓ Tomcat is running successfully"
                        echo "✓ Application deployed"
                        echo "Access your app at: http://$(curl -s ifconfig.me):8080/JavaLoginShowcase-1.0.0/"
                      else
                        echo "✗ Tomcat failed to start after deployment"
                        echo "Check logs: tail -50 /opt/tomcat/logs/catalina.out"
                      fi
                    else
                      echo "ERROR: Temp directory ~/tmp_deploy not found!"
                      exit 1
                    fi
                    
                    echo "=== Deployment Complete ==="
                  readyTimeout: '20000'